plugin:
  image: golang:1.6
  working_dir: /go/src/github.com/libnetwork-plugin/libnetwork-go
  command: /bin/bash -c "go run main.go"
  volumes:
    - ./libnetwork-go:/go/src/github.com/libnetwork-plugin/libnetwork-go
  expose:
    - "9000"
  ports:
    - "9000:9000"
  environment:
    - PLUGIN_SERVER_PORT=9000

tests:
  image: calico/test:latest
  working_dir: /code
  volumes:
    - ./:/code
  links:
    - plugin:plugin
  command: "nosetests tests.unit.driver_plugin_test -c nose.cfg"
  environment:
    - PLUGIN_SERVER_HOST=plugin
    - PLUGIN_SERVER_PORT=9000